on:
  push:
    branches:
      - main

name: Deploy template app to shinyapps.io

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}

    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("shiny", "rsconnect", "data.table", "readxl"))

      - name: 💎 Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: 'jules-dev'  # Your shinyapps.io account name
          SHINYAPPS_TOKEN: ${{ secrets.TOKEN }}  # Your shinyapps.io token
          SHINYAPPS_SECRET: ${{ secrets.SECRET }}  # Your shinyapps.io secret
        run: |
          library(rsconnect)
          rsconnect::setAccountInfo(
            name = Sys.getenv("SHINYAPPS_NAME"),
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(".")
